# Generated by Django 3.2.9 on 2022-03-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahajan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='Email',
            new_name='Last',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='Mobile',
        ),
    ]
